public class GoogleSearchButtonById {
    // <button id="gbqfba" aria-label="Google Search" name="btnK"
    //         class="gbqfba"><span id="gbqfsa">Google Search</span></button>
    public static void main(String[] args){
        WebDriver driver = new FirefoxDriver();
        driver.get("http://www.google.com");
        WebElement searchBox = driver.findElement(By.id("gbqfba"));
        searchBox.submit();
    }
}

// Each element is uniquely identified by an ID, if provided.
// An ID can be assigned manually be the developer or, most of the times, left to be
// dynamically generated by the server where the web application is hosted, and this ID
// can change over time